### ISSUE TITLE
Validator2 gives a java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by jihonsvik** [difi/vefa-validator#1]
Validator2 (http://vefa.difi.no/validator2/) gives an exception. Occurs when the xml-file is too big (4-5mb).
Screenshot of the exception with backtrace:
![f824b37e-31e8-11e5-8bc7-92c0ae4dc5c0](https://cloud.githubusercontent.com/assets/10721331/9060691/5dc9f5ba-3ab6-11e5-9bd8-59c74b921121.JPG)

**Comment by klakegg** [comment]
Please send a sample file to ehf@difi.no

**Comment by klakegg** [comment]
I guess our server is not scaled sufficiently for your file.

I've done a performance test using the file you sent to me, please check it out:
[Performance test #001](https://github.com/difi/vefa-validator/blob/a468cdbd56398f7bfbb31b2bc3dd48ca0458af7b/doc/test_performance_001.md)

**Comment by jihonsvik** [comment]
Thanks, the new version works great (http://test.vefa.difi.no/validator/).
FYI, not so often our customers generates files on this size, but it does happen occasionally.
