### ISSUE TITLE
Will Peppol validation artifacts be part of artifacts provided by DIFI vefa validation artifacts?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#10]
There is communique from OpenPeppol that new release of validation artifacts is available at : Release package: https://joinup.ec.europa.eu/svn/peppol/Validation Resources/BIS v2/BIS2.0-VA-V3.1.0_RC1.zip

9th of October 2015 is date of publish for that release. I want to know whether those updated validation rules will be part of validation artifacts provided by  DIFI : https://test-vefa.difi.no/validator/repo/ ?

If so, when we can get those artifacts for testing from https://test-vefa.difi.no/validator/repo/ ?

**Comment by klakegg** [comment]
The Difi test validator were updated with the latest version of the OpenPEPPOL release before published on JoinUp. What was the problem?

**Comment by aaron-kumar** [comment]
My only aim was to get confirmation  I know Peppol artifacts are already there in repo : https://test-vefa.difi.no/validator/repo/ . But I want to get confirmation that whether you included latest peppol validation artifacts those are mentioned in communique?. From your reply, it look like : "YES"

**Comment by aaron-kumar** [comment]
Found communique: http://vefa.difi.no/ehf/announcement/2015-09-03-delay-in-release-for-review-of-ehf-artefacts/
