### ISSUE TITLE
Are validation artifacts available at test site : https://test-vefa.difi.no/validator/repo/ are final now?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#11]
I want to know whether validation artifacts available at: https://test-vefa.difi.no/validator/repo/ are final now? These will be same artifacts that will be used in http://vefa.difi.no/validator/repo/ from 1st October, 2015?   OR  Those are still work in progress?

I want to know exact date of finalization of artifacts?

**Comment by klakegg** [comment]
Please provide me the result of the review ending September 30, then I'll answer your questions.

**Comment by aaron-kumar** [comment]
It will be good if you provide straight-forward answer. That will be helpful for everyone. Question in response of question is not good. 

You could have answer my question like this: 
"We are waiting for review results. There is review window till September 30, 2015. If everything is ok (review approved) on said date, than those artifacts will be final and will be deployed to http://vefa.difi.no/validator/repo/ "

**Comment by aaron-kumar** [comment]
Found communique: http://vefa.difi.no/ehf/announcement/2015-09-03-delay-in-release-for-review-of-ehf-artefacts/
