### ISSUE TITLE
PEPPOL v1 ASiCE files?

### ISSUE THREAD

**Issue by jphuttunen** [difi/vefa-validator#13]
Current production version of Validation Artifacts do not include any PEPPOL v1 files (e.g. for Orders and Order Confirmations). Are these available from somewhere?

Validation Artifacts for testing do include v2 of PEPPOL profiles, but these will not be used until october-november.

**Comment by klakegg** [comment]
PEPPOL BIS v1 is deprecated as of spring 2017.
