### ISSUE TITLE
Online Test validator (https://test-vefa.difi.no/validator/) is not working since last 16 hours, error : 504 Gateway Time-out

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#15]
Online Test validator (https://test-vefa.difi.no/validator/) is not working from since 16 hours. 

I am getting error: 504 Gateway Time-out

Can you either rectify it or provide me direct support email id?

**Comment by aaron-kumar** [comment]
Good to find that online test validator is now available. : https://test-vefa.difi.no/validator/

It was offline/not available for more than 50-55 hours. 

Can you share support email id just in case?

**Comment by klakegg** [comment]
I have no clue what to change in the repo as response to this issue. This is the issue tracker for the code in repository, and not at all about operations. Please use the Difi support addresses, as always, for contact regarding our non 24/7 services.
