### ISSUE TITLE
Validator missing necessary documentation and architecture detail

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#2]
It will be better if new validator contain architecture description like components interaction and deployment diagram 

In addition, it will be good to have detailed documentation about:
* Information about validation artifacts
* how to load validation artifacts
* How to modify validation artifacts
* What is the purpose of Test and Production artifacts 

It is bit difficult to go through each module code to find out what it contains and how things should be deployed

Can you please extend README file and explain the usage of each module?

**Comment by klakegg** [comment]
Please see the "Getting started". This is not a project to deploy, this is a library to use.

Documentation will be added as the project goes on.

**Comment by aaron-kumar** [comment]
So you means "validatior-web" and associated modules are for DiFI's internal use?  
It implies that with this release of validator, AP need Not to deploy validator-web on its own server as was the case with previous (old) validator. 

AP only need to include dependency of validator-core and based on source (
"Production" or "Test")  validation results will be published by validator-core. 

If this is the case, then it is great improvement on validator and it was well anticipated. Thanks for making it so easy to integrate. 
P.S.
Difi will maintain those artifacts:
"Production" : http://vefa.difi.no/validator/repo/
"Test" : http://test-vefa.difi.no/validator/repo/ --Upcoming

**Comment by klakegg** [comment]
I think our current README gives a solid hint to everyone on how to use the validator.

**Comment by aaron-kumar** [comment]
Thanks for making changes in README file
