### ISSUE TITLE
Unable to detect profileid with "large" amounts of elements in UBLExtensions

### ISSUE THREAD

**Issue by esbenbach** [difi/vefa-validator#20]
Cross post issue from Linkedin (https://www.linkedin.com/groups/4647203/4647203-6075233828534841345)

If an Invoice file has too much data in the UBLExtensions section an error is thrown by the validator - SYSTEM-001 Unable to detect ProfileId. 

An example of an extension section that causes the error: http://pastebin.com/rR8P7Phc
Remove on "DeliveryItems" section and the document will not throw the ProfileId error.

**Comment by klakegg** [comment]
Use of UBLExtensions is currently out of scope for EHF and PEPPOL BIS. Validator provided by Difi is not to created to cover usage not part of standard.
