### ISSUE TITLE
Could not initialize class no.difi.vefa.validator.ValidatorBuilder

### ISSUE THREAD

**Issue by rdineshrs** [difi/vefa-validator#23]
it was working before

       public synchronized Validator getValidator() throws Exception { 
        if (validator == null) {
                  validator = ValidatorBuilder.newValidator().setSource(new DirectorySource(Paths.get(getClass().getResource("/repo").toURI()))).build();
        }
        return validator;
    }

</style> </head><body><h1>HTTP Status 500 - java.lang.NoClassDefFoundError: Could not initialize class no.difi.vefa.validator.ValidatorBuilder</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>java.lang.NoClassDefFoundError: Could not initialize class no.difi.vefa.validator.ValidatorBuilder</u></p><p><b>description</b> <u>The server encountered an internal error (java.lang.NoClassDefFoundError: Could not initialize class no.difi.vefa.validator.ValidatorBuilder) that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class no.difi.vefa.validator.ValidatorBuilder

**Comment by klakegg** [comment]
NoClassDefFoundError is clearly not an exception from within the library. Are you sure you included validator-core in you project?

**Comment by rdineshrs** [comment]
ya. i including the latest validator-core 

<dependency>
            <groupId>no.difi.vefa</groupId>
            <artifactId>validator-core</artifactId>
            <version>2.0.2</version>            
   </dependency>

**Comment by klakegg** [comment]
Still, NoClassDefFoundError is not triggered by vefa-validator, and this is related to your project/environment.

**Comment by rdineshrs** [comment]
actually i am trying to expose web service using jersey frame work

**Comment by klakegg** [comment]
How is Jersey in your project related to the exception?

**Comment by rdineshrs** [comment]
My code

    public static Validator validator;
     validator = ValidatorBuilder.newValidator().setSource(new DirectorySource(Paths.get(getClass().getResource("/repo").toURI()))).build();

**Comment by klakegg** [comment]
How is your code related to NoClassDefFoundError?

**Comment by rdineshrs** [comment]
while calling the **ValidatorBuilder.newValidator()**  i am facing
Could not initialize class no.difi.vefa.validator.ValidatorBuilder

**Comment by klakegg** [comment]
No, the exception occurs earlier, unless you can provide me with an exception referencing **the line** in your code.
