### ISSUE TITLE
Why can't current vefa-validator generate "Message Level Validator" for document it validates?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#25]
Note: It is suggestion, not an issue.

Why can't current vefa-validator generate "Message Level Response" for document it validates?

Vefa-Validator can detect following errors in document to be validated:
1. Validation error of type fatal
2. Validation error of type warning. Warnings only will NOT cause rejection of the business document.
3. Wrong version of business document (Will be handled like validation error of type error)
4. Empty XML elements and attributes (Will be handled like validation error of type warning)

Based on validation result, It can generate MLR (UBL2.1- ApplicationResponse) .

**Comment by klakegg** [comment]
This validator will not implement MLR as that would be cluttering of responsibilities.
