### ISSUE TITLE
Not able to deploy "Vefa Validator :: Web" over Glassfish.

### ISSUE THREAD

**Issue by folia2001** [difi/vefa-validator#26]
Hi.  Can anybody help me with this?  I've just downloaded the complete solution and tried to run the Web project without changing anything (just to start over a runnable solution).  

Up to now, I'm not able to get it running.... and the exception I get every time I try to deply the application is as follows:
remote failure: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'validatorService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.google.common.collect.Sets.newConcurrentHashSet()Ljava/util/Set;

I would really appreciate any clue on this.

Thank you!

**Comment by klakegg** [comment]
This is related to Glassfish and can not be fixed by changing this project.
