### ISSUE TITLE
VAT rates

### ISSUE THREAD

**Issue by stoivo** [difi/vefa-validator#27]
Hi,

Currently we are are working on tax categories, and testing different percentage.
We were trying to send invoice with wrong VAT rate percent and got no error on vefa-validator.

Example:
```xml
<cac:TaxCategory>
  <cbc:ID schemeID="UNCL5305">AA</cbc:ID>
  <cbc:Percent>9.0</cbc:Percent>
  <cac:TaxScheme>
    <cbc:ID>VAT</cbc:ID>
  </cac:TaxScheme>
</cac:TaxCategory>
```

9% VAT rate with code ‘AA’ does not exist, but still we didn't get any errors.

Also since VAT rate 8% has been increased to 10% since Jan 1st 2016, we should get some warning possibly based on invoice issue date if the VAT rate is not in use instead of just checking VAT category (code). 

Example: 
If invoice issue date is Dec 1st 2015, and has VAT rate 10% (AA) => error, rate is not active, same goes other way around, if invoice issue date is Jan 10th 2016, and has VAT rate 8% (AA) => error, rate is not active.

**Comment by klakegg** [comment]
The validator code itself does not contain any rules, this issue is not related to anything in this repository.

**Comment by stoivo** [comment]
I have seen that difi Vefa validator have some validations on other rules like, VAT codes must be one of the following codes
![vat_categories_validator](https://cloud.githubusercontent.com/assets/3492040/15472286/965be2fa-20fa-11e6-95a3-ac68c12c1262.png)

Why shouldn't the validator include validations for this case? 

Maybe I am asking on the wrong repository. If this is not the correct repository, where can I find that repository?

**Comment by tyskjohan** [comment]
Try the difi/vefa-validator-conf repository
