### ISSUE TITLE
any doc on how to build it or use it?

### ISSUE THREAD

**Issue by simakas** [difi/vefa-validator#28]
any doc on how to build it or use it?

**Comment by klakegg** [comment]
This library is built using Maven.

**Comment by simakas** [comment]
that part is clear, any example of how to include the api and start using it?

**Comment by klakegg** [comment]
Please see the README.md in project root.

**Comment by simakas** [comment]
i wouldn't be asking without reading it. to me it looks a little short sighted. does it have to be maven project or can it be used in java directly? if so, can you tell which libraries have to be included? trying to migrate from vefa-validator-app and this looks a little stub.

**Comment by klakegg** [comment]
Dependencies are managed using Maven.
