### ISSUE TITLE
'PEPPOL BIS 01A Catalogue Only 2.0' setup error

### ISSUE THREAD

**Issue by monze** [difi/vefa-validator#31]
Hello

Found a small error in your online validator: https://vefa.difi.no/validator/.
I try to validate a PEPPOL BIS 01A Catalogue Only 2.0 document.

I'm using this document
```
<Catalogue xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Catalogue-2" xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Catalogue-2 ../UBL%202.1%20schema/maindoc/UBL-Catalogue-2.1.xsd">
   <cbc:UBLVersionID>2.1</cbc:UBLVersionID>
   <cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns019:ver2.0:extended:urn:www.peppol.eu:bis:peppol1a:ver2.0</cbc:CustomizationID>
   <cbc:ProfileID>urn:www.cenbii.eu:profile:bii01:ver2.0</cbc:ProfileID>
   ...
```

This result in that I get an error from a resource called 'ubl-despatchadvice-2.1', as showed here: 
```
 PEPPOL BIS Catalogue 2.0 (Profile 01)
 Download source  1ms  peppolbis-t19-01-2.0  f06eabf8f5635f7e3d06b33a4626dc8c2e76869a
 FATAL
 XSD validation
 1ms  ubl-despatchadvice-2.1  d6122e53220eb8e2732ef0d0c7474b21
 FATAL
 XSD cvc-elt.1: Cannot find the declaration of element 'Catalogue'.
```

I thing the wrong Schema is used, as it is named DespatchAdvise, which is a completely different document type.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
This repository does not contain configuration for PEPPOL BIS.

**Comment by monze** [comment]
I'm sorry that I postes this error in the wrong repository. 
Where should it has been posted instead? Or can I assume that you (klakegg) has created a new issue in the correct repository, now that you have closed the issue in this repository?

If I go to Difi validator [https://vefa.difi.no/validator/]( https://vefa.difi.no/validator/), it does state that PEPPOL BIS is a supported standards, and the other PEPPOL BIS documents can be validated.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
This is clearly an issue related to rules for PEPPOL BIS, not the software in the repository. This is also not an issue tracker for all kinds of errors in an running instance.
