### ISSUE TITLE
CustomizationID for PEPPOL BIS 01A Catalogue Only 2.0

### ISSUE THREAD

**Issue by monze** [difi/vefa-validator#32]
Hello

Found another small error in your online validator: https://vefa.difi.no/validator/.
I tried to validate a PEPPOL BIS 01A Catalogue Only 2.0 document. If I download peppol test files from
https://joinup.ec.europa.eu/svn/peppol/PostAward/CatalogueOnly1A/
the catalogue files is identified. These test files have the CustomizationID:
```
urn:www.cenbii.eu:transaction:biitrns019:ver2.0:extended:urn:www.peppol.eu:bis:peppol1a:ver2.0
```

However the documentation state that the CustomizationID must be:
```
urn:www.cenbii.eu:transaction:biitrns019:ver2.0:extended:urn:www.peppol.eu:bis:peppol1a:ver4.0
```
Note the ending must be '4.0' and not '2.0'.

So when I update the CustomizationID to the correct value, the 'PEPPOL BIS 01A Catalogue Only 2.0 document' it can no longer be identified by your validator.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
This repository does not contain configuration for PEPPOL BIS.
