### ISSUE TITLE
<cbc:DocumentType> elektroniskB2Cfaktura

### ISSUE THREAD

**Issue by knutia** [difi/vefa-validator#33]
validatoren gir

error når <cac:PartyLegalEntity>/<cbc:CompanyID> mangler når en gjennofakturerer til privat personer som ikke har organisasjons nummer.

warnng når <cac:PartyLegalEntity> mangler og <cbc:InvoiceTypeCode> er Z02 eller 380

**Comment by klakegg** [comment]
Denne issue-trackeren er for feil relatert til validator-programvaren, ikke for saker relatert til regler som benyttes sammen med validatoren.

**Comment by knutia** [comment]
ok, men hvor skal saker relatert til regler som benyttes sammen med validatoren registreres?
