### ISSUE TITLE
Performance hit after the latest validation rules.

### ISSUE THREAD

**Issue by m4caron** [difi/vefa-validator#36]
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Issue is not related to specific validation rules for any domain.
- [x] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
Hi, I have been running the original version of the validator 2.0. However after the latest rule update in the middle of november, validation speed of the validator went from roughly 100 validations/s to 4 validation/s. Which is really not acceptable and I am wondering what is the cause of this?

I thought maybe there were some changes in the later versions of the validator, that improve the performance with the latest rules, so I updated to the latest release version 2.0.2, but the problem still persists. If the latest rules are used, validation is incredibly slow, roughly 4 validations per second. As soon as I switch to the previous rule set, everything is fine and the speed is back to 100 validations/s.

Can you advise us what might be the problem?

**Comment by klakegg** [comment]
This issue is not related to the validator software.
