### ISSUE TITLE
Custom validation rules

### ISSUE THREAD

**Issue by mikkelbm** [difi/vefa-validator#37]
- [ ] Issue is not related to specific validation rules for any domain.
- [X] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:

Hi

We are in the process of moving from the Vefa Validation framework v. 1 to this new implementation. And it looks promising. 
In the old framework there is a vefa-validation-conf folder which contains some configurations about how the documents should be validated. And we were able to put in our own validation-rules.

Can this be done with the new version 2.0? And if yes - how?

Thanks in advance...

/Mikkel

**Comment by klakegg** [comment]
Back when we release version 2 answered everyone that they did not use the opportunity to add their own rules, thus is this not taken fully care of. Any information related to this may be available for version 3.

**Comment by mikkelbm** [comment]
Ok... Thanks for your answer. We would like this feature to be re-implemented in future versions :)
