### ISSUE TITLE
commandline interface and package usage

### ISSUE THREAD

**Issue by simakas** [difi/vefa-validator#39]
is there any commanline interface in this package that could be used? or API like interface for posting or that some interface that supported streams?
if I understand it correctly it provides some java libs to be used in java project, in my case I have no use of java libs, since xmls are generated in non-java environment.

**Comment by klakegg** [comment]
This project provides a validation library. Anyone who uses the library is free to implement the interface required to fit the specific requirements.

**Comment by simakas** [comment]
Any example or enviroment on where to use the lib?

**Comment by klakegg** [comment]
Please see the README regarding use of the library.
https://github.com/difi/vefa-validator/blob/master/README.md

**Comment by simakas** [comment]
I did and thats why im asking here, what kind of environment is it suppose to be included in? does it only work as part of mvn project or can I include it like a java lib? if so, which packages are suppose to be included? tried including it into dummy mvn project, but classes are not being found. can you update the docs to be more specific or include details about the environment its suppose to be included in? or include some dummy project in case its only working as mvn include?

**Comment by klakegg** [comment]
We use Maven to handle dependencies, enabling all Java-environments supporting Maven-style dependency management (gradle, sbt, leiningen, ...). Using tools to handle project dependencies is according to current best practice, so there are no need for us to neither maintain a list of all dependencies nor providing a dummy project.
