### ISSUE TITLE
Validator handling of rule prefixes

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator#44]
Please make sure these boxes are checked before submitting your issue - thank you!

- [x] Issue is not related to specific validation rules for any domain.
- [x] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
svrl:text element containing rule description used to be formatted like <svrl:text>[EUGEN-T10-R012]-An allowance percentage MUST NOT be negative.</svrl:text>, now it is something like: <svrl:text>Document SHOULD not contain schema location.</svrl:text>, so, as you can see, it is missing [RULE_ID]- prefix (square brackets opening, rule id, square brackets closing, dash) and I suppose Vefa validator library (we are using version 2.0.2, latest available on Maven repo) has handling for such prefix, resulting in having UNKNOWN as a value for (failed) assertion identifier.

Is that also intended behavior (seems like not, updating schematrons probably would be cheaper and faster than changing library, testing it, publishing on Maven repo)

**Comment by klakegg** [comment]
Any "[RULE_ID]-" prefix is not according to Schematron standard where the attribute `id` is supposed to be used for identification of assertion.
