### ISSUE TITLE
Consistant Inconsistant in EHF Validation using v2.0.2 and the new Validation artifacts

### ISSUE THREAD

**Issue by christian-andersson** [difi/vefa-validator#45]
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Issue is not related to specific validation rules for any domain.
- [X] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
(Not sure if it is the validation rules itself that is causing this problem or the validation engine)

With the new Validation rules from Difi fr om 2017-11-15 located on https://vefa.difi.no/validator/repo/ we get inconsistent validation depending on which EHF file we are trying to validate first.

I have prepared a package showcasing the problem that I will attach. but I will describe it here also.

I have 3 EHF files that I want to validate, depending on the order I validate these (in the same instance of the validator) I get consistent inconsistense in their success or failure to validate.
IF I run the validation of these three EHF files in all permutations (6 executions) I get the following table of success or fail. (Each execution starts with a new startup of the java executable, but each file in the execution is using the same validator instance, since it is not possible to setup multiple instances)

files/executions | 1,2,3 | 1,3,2 | 2,1,3| 2,3,1| 3,1,2| 3,2,1
----------------|------|------|------|------|-----|------
1.xml | success | success | success | success | failure | failure
2.xml | failure | failure | success | success | failure | failure
3.xml | failure | failure | failure | failure | success | success

now, this is an inconsistency that we cannot understand because this inconsistency is very consistent, ie every time I have run this, I have gotten the very same results.

From the looks of it, it seems that the very first EHF always succeeds and the rest depends on what the previous validation result (in the same execution)

The above results was created on MacOS High Sierra using 
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

and I am also getting the same problem on linux using
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by christian-andersson** [comment]
The Test files
[validatortest.zip](https://github.com/difi/vefa-validator/files/1481352/validatortest.zip)

**Comment by klakegg** [comment]
We don't like duplication of issues. Is this related to the validator code?

**Comment by christian-andersson** [comment]
As I wrote initially in the issue, I have no idea. Since this is the first time I have seen this behaviour, and because it happens with the new validation rules, it would be easy to assume that the problem lies in the new ValidationRules, but at the same time, as far as I know, the validation rules are only xslt style sheets, and afaik this type of behaviour (remembering stuff from one execution to another) should not be possible, this is the reason why the issue has been duplicated.

**Comment by christian-andersson** [comment]
Seems like the problem was in saxon.
in commit 89ec2e the problem still existed, but in commit c3744a4 where you bumped version of saxon from 9.7.0-1 to 9.7.0-4 the problem did not exist.

It has also been tested using the 2.0.2 version but using the new version of saxon, and it works.
