### ISSUE TITLE
Validator incorrectly marks a valid invoice as invalid (FATAL) when validating multiple invoices with same Validator instance

### ISSUE THREAD

**Issue by igororlov** [difi/vefa-validator#47]
Please make sure these boxes are checked before submitting your issue - thank you!

- [X] Issue is not related to specific validation rules for any domain.
- [X] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
We (@cloudware) found out that when validating several invoices with the same validator (it should be fine, because, as you write, validator instance is costly to create), any of invoices from number 2 fails it the tax categories contained in it are different from tax categories in the first invoice that has been validated. Seems that taxCategories are just cached from first invoice and are not being reset later. There's a big chance that the problem exists for a long time, but it started failing recently after making validation rules stricter in this commit: https://github.com/difi/vefa-ehf-postaward/commit/d9ad903f50f29ae09c1d69e5d078793a12c7fd7b#diff-4ccbac98c0978d1000e11e8be6d3686a (rule NONAT-T10-R031).

We have sent an email to @klakegg two days ago (05.12.2017) but didn't get any response yet.

**Comment by mjiderhamn** [comment]
We are seeing the same issue (also with `NONAT-T10-R031`). There is a workaround/solution mentioned in #46, which we haven't confirmed yet.

**Comment by mjiderhamn** [comment]
Updating Saxon as of #46 did not seem to resolve the issue for us.

**Comment by mattiz** [comment]
We also experience the same issue with `NONAT-T10-R031`. The workaround in #46 seem to solve the problem.
