### ISSUE TITLE
validator-core use Java 7 specific feature (NIO - Filesystem, Path), legacy system which are on lower java version will not work out of box

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-validator#5]
It is found that validator-core is using java 8 specific feature. There are legacy system which are still working on lower java version. 

Either you should support lower java version (at least java 6) or provide way to extend the validator-core to support that lower version. 
If you can't support lower version than at least you should provide way to extend.

**Comment by m4caron** [comment]
I'm not sure Aaron, cause I built it underv version 1.7 and have been successfully running it under version 1.7 so far. So I don't think 1.8 is required, but 1.7 probably is.

**Comment by aaron-kumar** [comment]
Yes, it will work java 7 because it support nio.  Most of code dealing with directory source make use of java.nio. This is something missing in java 6.

**Comment by m4caron** [comment]
Yes, that's true, I had to upgrade our project from 1.5 to 1.7 because of it.

**Comment by klakegg** [comment]
Using a 4 years old version of Java in a brand new project is fair. As this project relies heavily on functionality introduced by Java 7, requiring Java 7 is natural. This project doesn't force any particular architecture, thus doesn't force projects using this library to be neither Java nor Java 7.

**Comment by aaron-kumar** [comment]
I want clarity on below statement:
>>This project doesn't force any particular architecture, thus doesn't force projects using this library to be neither Java nor Java 7

So that means we have to develop our own validator (using same artifacts), if we are using any other language or lower java version. right?

**Comment by kjorlaug** [comment]
If you're not able to use the new validator nativly due to java version, then the best route is to facade it, i.e. by developing (and sharing?) your own webservice interface for it (ref #6). Other options would be to upgrade your project or adapt/modify the validator (the latter not recommended)

@klakegg's point is that we don't want to force the use of an spescific architecture like webservices, hence it's been made the way it has been made.

**Comment by aaron-kumar** [comment]
Yes, for someone if upgrading java not possible right now then facade is best option. This was but I was thinking and already started implementing it.
