### ISSUE TITLE
Q: Will there be a common Validator WebService, or should users build their own if needed?

### ISSUE THREAD

**Issue by jphuttunen** [difi/vefa-validator#6]
In the previous incarnation of the Validator, there was a web service application that could be used to validate contents programmatically. Has that web service been ditched altogether in the new Validator? Currently it seems there is only an interactive web app for validating.

**Comment by aaron-kumar** [comment]
New validator is just library that is used to validate EHF and peppol BIS (3A, 4A, 5A) documents. You must pass artifacts source directory as parameter in addition to document to be validated, Artifact source directory must be available on your local subsystem. 

New validator DO NOT require web-service hit. 

Webapp that you are talking about is not used programmatically. It is just for DIFI internal use or if your conversion specialist want to test the conversion.

**Comment by klakegg** [comment]
The new validator is a library supported by validation artifacts for EHF, UBL 2.0, UBL 2.1 and PEPPOL BIS (partial at the moment).

You are free to encapsulate the library in any way best suited your needs, and WebService may be a solution for you based on your architecture.

@aaron-kumar The sample web application is the validator exposed externally by Difi.

**Comment by aaron-kumar** [comment]
@klakegg : I want to say same about sample web application. Just usage of wrong words from my side. 

Regarding PEPPOL BIS, what is plan ? Will you support it fully or partially.

**Comment by jphuttunen** [comment]
OK, thank you for the answer, it clarifies/solves the issue.
