### ISSUE TITLE
The actual validation rules are in an .asice file and not browseable

### ISSUE THREAD

**Issue by tyskjohan** [difi/vefa-validator#7]
The fact that the actual validation rules files are inside .asice files makes it diffcult to browse them on GitHub and difficult to propose improvements/pull requests.

**Comment by klakegg** [comment]
Source of validation rules inside asice-files are Github, thus this doesn't change the browsability of Github.

**Comment by tyskjohan** [comment]
This is not clear to me. Where is this source? It if is https://github.com/difi/vefa-validator-conf then this text should be changed: "The validator application belonging to this project will be abandoned October 1st, 2015. Make sure to migrate to the new validator." by adding something like "However, the validation rules for the new validator are still maintained in this repository (vefa-validator-conf)."

**Comment by klakegg** [comment]
In the project containing validation **configuration** is the text "The validator **application** belonging to this project will be abandoned October 1st, 2015. Make sure to migrate to the new **validator**." pointing to the abandoning of the old validator **application** correct.

**Comment by tyskjohan** [comment]
Yes, and that text suggests that the current validator gets its rules elsewhere - by saying "the validator belonging" and not "one of the validators belonging" or "a validator belonging"
