### ISSUE TITLE
My app downloads artifacts from internet

### ISSUE THREAD

**Issue by jangj** [difi/vefa-validator#8]
Hi.

I managed to build the example program using Netbeans, but every time I run it, it downloads the artifacts from http://vefa.difi.no/validator/repo/.

Where should I put the downloaded artifacts, and how do I get my java app to use these instead?
The 'old' validator was configured in validator.properties file and config.xml file, but where do I configure this?

Im sure its there somwhere in the code but I just cant figure it out. I have zero Java experience.

-Jan

**Comment by klakegg** [comment]
I'd suggest reading the readme-file.
https://github.com/difi/vefa-validator/blob/master/validator-web/README.md
