### ISSUE TITLE
Deployment in Wildfly / Jboss

### ISSUE THREAD

**Issue by thomasnakken** [difi/vefa-validator#9]
Have you tried to deploy this app in jobs / wildly? We get the following error:
java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider com.sun.nio.zipfs.ZipFileSystemProvider not found

Do you have any suggestion on how to solve this deployment issue?

**Comment by klakegg** [comment]
This project is tested using Oracle Java 7/8 and OpenJDK 7. This is a new issue to me, and I have no other suggestions than try to use a different JDK.

**Comment by thomasnakken** [comment]
The problem is not in the JDK. Same idk used for both wildly 8.2 and tomcat. Application works in tomcat but not in wildfly.

Solution is to remove Jimfs.newFileSystem(com.google.common.jimfs.Configuration.unix()) and change it with 

    Path path = Paths.get("some path"); 
  fileSystem = path.getFileSystem();

**Comment by thomasnakken** [comment]
Found the problem; Wildfly does not load java servicemodules - the solution is to check if Jims is loaded - if not create it by hand. Cound be nice to add this in so it work on all platforms


 public AbstractSourceInstance() {
        List<FileSystemProvider> list = JimfsFileSystemProvider.installedProviders();
    try {
        URI uri = new URI("jimfs", "vefa", null, null);
        ImmutableMap<String, ?> env = ImmutableMap.of("config", Configuration.unix());
        for (FileSystemProvider provider : list) {
            if (provider instanceof JimfsFileSystemProvider) {
                JimfsFileSystemProvider jimfsFileSystemProvider = (JimfsFileSystemProvider) provider;
                fileSystem = jimfsFileSystemProvider.newFileSystem(uri, env);
            }
          }
        if (fileSystem == null)
        {
            JimfsFileSystemProvider jimfsFileSystemProvider = new JimfsFileSystemProvider();
            fileSystem = jimfsFileSystemProvider.newFileSystem(uri,env);
        }
    }catch(Exception e)
    {
        throw new RuntimeException("Unable to create VEFA Validator instance",e);

    }


    }
